# Generated by Django 3.1.7 on 2021-03-19 10:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '聊天室',
                'verbose_name_plural': '聊天室',
                'db_table': 'chat_room',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='信息内容')),
                ('time', models.CharField(max_length=255, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('read', '已读'), ('unread', '未读')], default='read', max_length=30, verbose_name='是否已读')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom', verbose_name='聊天室')),
            ],
            options={
                'verbose_name': '聊天信息',
                'verbose_name_plural': '聊天信息',
                'db_table': 'message',
            },
        ),
    ]
