# Generated by Django 3.1.7 on 2021-05-25 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20210525_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatRoom_msg', to='chat.chatroom', verbose_name='聊天室'),
        ),
        migrations.CreateModel(
            name='GroupMessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', '已读'), ('unread', '未读')], max_length=10, verbose_name='是否已读')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmsg_status', to='chat.message', verbose_name='所属信息')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_gmsgStatus', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '群聊信息状态',
                'verbose_name_plural': '群聊信息状态',
                'db_table': 'group_msg_status',
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='信息内容')),
                ('time', models.CharField(max_length=255, verbose_name='创建时间')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatRoom_g_msg', to='chat.chatroom', verbose_name='聊天室')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_g_msg', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '群聊信息',
                'verbose_name_plural': '群聊信息',
                'db_table': 'groupChat_message',
            },
        ),
    ]
