# Generated by Django 3.1.7 on 2021-05-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210525_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessagestatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmsg_status', to='chat.groupmessage', verbose_name='所属信息'),
        ),
    ]
